services:
  web:
    build: .
    ports:
      - "5123:5123"
    volumes:
      - .:/app
      - "${NAS_MOUNT_PATH:-/mnt/nas}:/mnt/nas"  # Use an environment variable with a default
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_PATH=/mnt/nas/soil_test_results.db  # Use environment variable in the app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:5123"]
      interval: 2s
      timeout: 10s
      retries: 5
    
