services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5123:5123"
    volumes:
      - ".:/app"
      - "${NAS_MOUNT_PATH}:/mnt/irds"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      DATABASE_PATH: /mnt/irds/soil_test_results.db
      SMB_USERNAME: "${SMB_USERNAME}"
      SMB_PASSWORD: "${SMB_PASSWORD}"
      REAL_NAS: "${REAL_NAS}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5123"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  smb:


