"""Initial migration

Revision ID: d2334e7192ac
Revises: 
Create Date: 2024-10-08 07:13:32.273389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2334e7192ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('added_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instances',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('instance_name', sa.String(), nullable=False),
    sa.Column('instance_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('instance_id')
    )
    op.create_table('spreadsheets',
    sa.Column('spreadsheet_id', sa.Integer(), nullable=False),
    sa.Column('spreadsheet_name', sa.String(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('spreadsheet_id'),
    sa.UniqueConstraint('spreadsheet_name')
    )
    op.create_table('spreadsheet_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spreadsheet_id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.instance_id'], ),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.spreadsheet_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spreadsheet_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spreadsheet_id', sa.Integer(), nullable=False),
    sa.Column('time_start_of_stage', sa.Float(), nullable=True),
    sa.Column('shear_induced_PWP', sa.Float(), nullable=True),
    sa.Column('axial_strain', sa.Float(), nullable=True),
    sa.Column('vol_strain', sa.Float(), nullable=True),
    sa.Column('induced_PWP', sa.Float(), nullable=True),
    sa.Column('p', sa.Float(), nullable=True),
    sa.Column('q', sa.Float(), nullable=True),
    sa.Column('e', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['spreadsheet_id'], ['spreadsheets.spreadsheet_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spreadsheet_rows')
    op.drop_table('spreadsheet_instances')
    op.drop_table('spreadsheets')
    op.drop_table('instances')
    op.drop_table('added_columns')
    # ### end Alembic commands ###
